"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { CalendarDays, Check, Copy, CreditCard, LockKeyhole, Settings, Trash2, UserRound, UserRoundCheck, Users, QrCode } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import MenuLateralPadrao from "../components/MenuLateralPadrao";
import CabecalhoPadrao from "../components/CabecalhoPadrao";

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

type TipoPessoa = "socio" | "nao_socio";
type Espaco = { id:string; nome:string; categoria:string; cobranca:"hora"|"diaria"; precoSocio:number; precoNaoSocio:number; permiteNaoSocio:boolean; capacidade?:string };
type Socio = { id:string; matricula:string|null; nome:string; cpf:string|null };
type Reserva = { id:string; espacoId:string; socioId:string|null; data:string; horario:string; nome:string; tipoPessoa:TipoPessoa; valor:number; status:"confirmada"|"cancelada"; pagamento:"pendente"|"pix" };
type PixConfig = { id:string; chave_pix:string|null; nome_recebedor:string; cidade:string; copia_e_cola:string; ativo:boolean };

const INICIAIS:Espaco[]=[
 {id:"fut",nome:"Quadra de Futebol",categoria:"Esporte",cobranca:"hora",precoSocio:100,precoNaoSocio:0,permiteNaoSocio:false},
 {id:"volei",nome:"Quadra de Vôlei",categoria:"Esporte",cobranca:"hora",precoSocio:50,precoNaoSocio:0,permiteNaoSocio:false},
 {id:"areia",nome:"Quadra de Areia",categoria:"Esporte",cobranca:"hora",precoSocio:30,precoNaoSocio:0,permiteNaoSocio:false},
 {id:"q48",nome:"Quadra 48",categoria:"Esporte",cobranca:"hora",precoSocio:20,precoNaoSocio:0,permiteNaoSocio:false},
 {id:"q1",nome:"Quiosque 1",categoria:"Lazer",cobranca:"diaria",precoSocio:80,precoNaoSocio:0,permiteNaoSocio:false},
 {id:"q2",nome:"Quiosque 2",categoria:"Lazer",cobranca:"diaria",precoSocio:80,precoNaoSocio:0,permiteNaoSocio:false},
 {id:"q3",nome:"Quiosque 3",categoria:"Lazer",cobranca:"diaria",precoSocio:80,precoNaoSocio:0,permiteNaoSocio:false},
 {id:"salao_p",nome:"Salão Pequeno de Vidro",categoria:"Eventos",cobranca:"diaria",precoSocio:300,precoNaoSocio:600,permiteNaoSocio:true,capacidade:"50 pessoas"},
 {id:"salao_g",nome:"Salão Social Grande",categoria:"Eventos",cobranca:"diaria",precoSocio:900,precoNaoSocio:1800,permiteNaoSocio:true,capacidade:"300 pessoas"},
 {id:"ctg",nome:"Salão CTG",categoria:"Eventos",cobranca:"diaria",precoSocio:80,precoNaoSocio:0,permiteNaoSocio:false,capacidade:"150 pessoas"},
];
const HORARIOS=["08:00 - 09:00","09:00 - 10:00","10:00 - 11:00","18:00 - 19:00","19:00 - 20:00","20:00 - 21:00","21:00 - 22:00"];
const moeda=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dataBR=(v:string)=>v?v.split("-").reverse().join("/"):"—";

export default function ReservasPage(){
 const [publico,setPublico]=useState(false); const [aba,setAba]=useState<"reservar"|"reservas"|"admin">("reservar");
 const [espacos,setEspacos]=useState<Espaco[]>(INICIAIS); const [socios,setSocios]=useState<Socio[]>([]); const [reservas,setReservas]=useState<Reserva[]>([]);
 const [espacoId,setEspacoId]=useState(INICIAIS[0].id); const [socioId,setSocioId]=useState(""); const [nomeNaoSocio,setNomeNaoSocio]=useState("");
 const [data,setData]=useState(""); const [horario,setHorario]=useState(HORARIOS[0]); const [tipoPessoa,setTipoPessoa]=useState<TipoPessoa>("socio");
 const [etapa,setEtapa]=useState<"selecao"|"pagamento">("selecao"); const [ultimaReserva,setUltimaReserva]=useState<Reserva|null>(null); const [pix,setPix]=useState<PixConfig|null>(null);
 const [pixForm,setPixForm]=useState({chave_pix:"",nome_recebedor:"SOCIEDADE GUARANI",cidade:"AUGUSTO PESTANA",copia_e_cola:""}); const [salvandoPix,setSalvandoPix]=useState(false); const [msg,setMsg]=useState(""); const [erro,setErro]=useState(""); const [busca,setBusca]=useState(""); const [buscaSocio,setBuscaSocio]=useState("");
 useEffect(()=>{const p=new URLSearchParams(window.location.search); const pub=p.get("publico")==="1"; setPublico(pub); if(pub)setTipoPessoa("nao_socio"); try{const e=localStorage.getItem("guarani_espacos_reservas");const r=localStorage.getItem("guarani_reservas");if(e)setEspacos(JSON.parse(e));if(r)setReservas(JSON.parse(r));}catch{} void carregarSocios(); void carregarPix();},[]);
 useEffect(()=>{localStorage.setItem("guarani_espacos_reservas",JSON.stringify(espacos));},[espacos]);
 useEffect(()=>{localStorage.setItem("guarani_reservas",JSON.stringify(reservas));},[reservas]);
 async function carregarSocios(){const {data,error}=await supabase.from("socios").select("id,matricula,nome,cpf").order("nome");if(!error)setSocios(data||[]);}
 async function carregarPix(){const r=await fetch("/api/configuracao-pix",{cache:"no-store"});const d=await r.json();if(r.ok&&d.config){setPix(d.config);setPixForm({chave_pix:d.config.chave_pix||"",nome_recebedor:d.config.nome_recebedor,cidade:d.config.cidade,copia_e_cola:d.config.copia_e_cola});}}
 const disponiveis=useMemo(()=>tipoPessoa==="nao_socio"?espacos.filter(e=>e.permiteNaoSocio&&e.precoNaoSocio>0):espacos,[espacos,tipoPessoa]);
 useEffect(()=>{if(!disponiveis.some(e=>e.id===espacoId)&&disponiveis[0])setEspacoId(disponiveis[0].id)},[disponiveis,espacoId]);
 const espaco=espacos.find(e=>e.id===espacoId); const socioSelecionado=socios.find(s=>s.id===socioId); const valor=espaco?(tipoPessoa==="socio"?espaco.precoSocio:espaco.precoNaoSocio):0;
 const ocupados=useMemo(()=>reservas.filter(r=>r.status!=="cancelada"&&r.espacoId===espacoId&&r.data===data).map(r=>r.horario),[reservas,espacoId,data]);
 const sociosFiltrados=socios.filter(s=>`${s.nome} ${s.matricula||""} ${s.cpf||""}`.toLowerCase().includes(buscaSocio.toLowerCase()));
 const reservasFiltradas=reservas.filter(r=>`${r.nome} ${espacos.find(e=>e.id===r.espacoId)?.nome||""}`.toLowerCase().includes(busca.toLowerCase()));
 function continuar(){if(!espaco)return alert("Selecione um espaço.");if(tipoPessoa==="nao_socio"&&(espaco.precoNaoSocio<=0||!espaco.permiteNaoSocio))return alert("Este espaço não pode ser alugado por não sócios.");if(tipoPessoa==="socio"&&!socioSelecionado)return alert("Selecione um sócio cadastrado como responsável.");if(tipoPessoa==="nao_socio"&&!nomeNaoSocio.trim())return alert("Informe o nome do responsável não sócio.");if(!data)return alert("Selecione a data.");if(ocupados.includes(horario))return alert("Este horário já está ocupado.");setEtapa("pagamento");}
 function confirmar(){if(!espaco)return;const nome=tipoPessoa==="socio"?socioSelecionado!.nome:nomeNaoSocio.trim();const nova:Reserva={id:crypto.randomUUID(),espacoId,socioId:tipoPessoa==="socio"?socioId:null,data,horario,nome,tipoPessoa,valor,status:"confirmada",pagamento:pix?.copia_e_cola?"pix":"pendente"};setReservas(v=>[nova,...v]);setUltimaReserva(nova);setNomeNaoSocio("");setSocioId("");setEtapa("pagamento");setMsg("Reserva registrada. Faça o pagamento via PIX, se disponível.");}
 function cancelar(id:string){if(confirm("Cancelar esta reserva?"))setReservas(v=>v.map(r=>r.id===id?{...r,status:"cancelada"}:r));}
 function alterarPreco(id:string,campo:"precoSocio"|"precoNaoSocio",v:number){setEspacos(a=>a.map(e=>e.id===id?{...e,[campo]:Math.max(0,v),...(campo==="precoNaoSocio"?{permiteNaoSocio:v>0}: {})}:e));}
 function alternarNaoSocio(id:string){setEspacos(a=>a.map(e=>e.id===id?{...e,permiteNaoSocio:!e.permiteNaoSocio&&e.precoNaoSocio>0}:e));}
 async function salvarPix(){setSalvandoPix(true);setErro("");setMsg("");try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Sessão administrativa não encontrada.");const r=await fetch("/api/configuracao-pix",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(pixForm)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erro ao salvar PIX.");setPix(d.config);setMsg("PIX da Sociedade atualizado com sucesso.");}catch(e){setErro(e instanceof Error?e.message:"Erro ao salvar PIX.");}finally{setSalvandoPix(false);}}
 function copiarPix(){if(!pix?.copia_e_cola)return;navigator.clipboard.writeText(pix.copia_e_cola);setMsg("PIX copia e cola copiado.");}
 return <div className="min-h-screen bg-[#f8faf9] text-[#17382c]">{!publico&&<><CabecalhoPadrao/><MenuLateralPadrao/></>}<main className={`min-h-screen px-4 py-6 lg:px-7 lg:py-8 ${publico?"":"lg:ml-[220px]"}`}><div className="mx-auto max-w-[1400px] space-y-6">
 {publico&&<div className="flex items-center justify-between rounded-2xl border bg-white p-4 shadow-sm"><div><b className="text-[#005a3c]">SOCIEDADE GUARANI</b><div className="text-xs text-gray-500">Reserva para não sócios</div></div><button onClick={()=>window.location.href="/login"} className="rounded-xl border px-4 py-2 font-bold">Voltar ao login</button></div>}
 <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-gray-500">{publico?"Reserva online":"Administração"}</p><h1 className="text-3xl font-extrabold text-[#005a3c]">Reservas</h1><p className="text-sm text-gray-500">Quadras, quiosques e salões.</p></div>{!publico&&<div className="flex flex-wrap gap-2"><button onClick={()=>setAba("reservar")} className={`rounded-xl px-4 py-2.5 font-bold ${aba==="reservar"?"bg-[#005a3c] text-white":"bg-white"}`}>Nova reserva</button><button onClick={()=>setAba("reservas")} className={`rounded-xl px-4 py-2.5 font-bold ${aba==="reservas"?"bg-[#005a3c] text-white":"bg-white"}`}>Reservas</button><button onClick={()=>setAba("admin")} className={`rounded-xl px-4 py-2.5 font-bold ${aba==="admin"?"bg-[#005a3c] text-white":"bg-white"}`}><Settings className="mr-1 inline h-4 w-4"/>Configurações</button></div>}</div>
 {msg&&<div className="rounded-xl border border-green-200 bg-green-50 p-3 font-semibold text-green-700">{msg}</div>}{erro&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 font-semibold text-red-700">{erro}</div>}
 {(publico||aba==="reservar")&&<section className="grid gap-6 lg:grid-cols-[1fr_390px]"><div className="space-y-5">
 <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-extrabold text-[#005a3c]">1. Quem está fazendo a reserva?</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={()=>{if(!publico)setTipoPessoa("socio")}} disabled={publico} className={`rounded-2xl border-2 p-5 text-left ${tipoPessoa==="socio"?"border-[#005a3c] bg-[#e8f3ee]":"border-gray-200"} ${publico?"cursor-not-allowed opacity-50":""}`}><UserRoundCheck className="h-7 w-7 text-[#005a3c]"/><b className="mt-2 block">Sou sócio</b><span className="text-xs text-gray-500">Valor de associado.</span></button><button onClick={()=>setTipoPessoa("nao_socio")} className={`rounded-2xl border-2 p-5 text-left ${tipoPessoa==="nao_socio"?"border-[#f4b400] bg-[#fff8df]":"border-gray-200"}`}><UserRound className="h-7 w-7 text-[#8a6700]"/><b className="mt-2 block">Não sou sócio</b><span className="text-xs text-gray-500">Somente espaços liberados.</span></button></div></div>
 <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-extrabold text-[#005a3c]">2. Responsável</h2>{tipoPessoa==="socio"?<><input value={buscaSocio} onChange={e=>setBuscaSocio(e.target.value)} placeholder="Pesquisar sócio por nome ou matrícula..." className="mt-4 w-full rounded-xl border px-3 py-3"/><select value={socioId} onChange={e=>setSocioId(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-3 py-3"><option value="">Selecione um sócio cadastrado</option>{sociosFiltrados.map(s=><option key={s.id} value={s.id}>{s.matricula?`${s.matricula} · `:""}{s.nome}</option>)}</select>{socioSelecionado&&<div className="mt-3 rounded-xl bg-[#e8f3ee] p-3 text-sm"><b>{socioSelecionado.nome}</b>{socioSelecionado.matricula&&<span> · Matrícula {socioSelecionado.matricula}</span>}</div>}</>:<input value={nomeNaoSocio} onChange={e=>setNomeNaoSocio(e.target.value)} placeholder="Nome completo do responsável" className="mt-4 w-full rounded-xl border px-3 py-3"/>}</div>
 <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-extrabold text-[#005a3c]">3. Escolha o espaço</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{disponiveis.map(e=><button key={e.id} onClick={()=>setEspacoId(e.id)} className={`rounded-2xl border p-4 text-left ${e.id===espacoId?"border-[#005a3c] bg-[#e8f3ee]":"border-gray-200"}`}><b>{e.nome}</b><div className="mt-2 text-xs text-gray-500">{e.cobranca==="hora"?"Por hora":"Por diária"}{e.capacidade?` · ${e.capacidade}`:""}</div><div className="mt-2 font-extrabold text-[#005a3c]">{moeda(tipoPessoa==="socio"?e.precoSocio:e.precoNaoSocio)}</div></button>)}{disponiveis.length===0&&<div className="col-span-full rounded-xl bg-yellow-50 p-5 text-sm">Nenhum espaço está liberado para não sócios no momento.</div>}</div></div>
 </div><aside className="h-fit rounded-2xl border bg-white p-5 shadow-sm lg:sticky lg:top-6"><h2 className="text-xl font-extrabold text-[#005a3c]">4. Data e horário</h2><label className="mt-4 block text-xs font-bold uppercase text-gray-500">Data<input type="date" value={data} onChange={e=>setData(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-3"/></label>{espaco?.cobranca==="hora"&&<label className="mt-4 block text-xs font-bold uppercase text-gray-500">Horário<select value={horario} onChange={e=>setHorario(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-3">{HORARIOS.map(h=><option key={h} disabled={ocupados.includes(h)}>{h}{ocupados.includes(h)?" — ocupado":""}</option>)}</select></label>}<div className="mt-4 rounded-xl bg-[#e8f3ee] p-4"><div className="text-xs text-gray-500">Total</div><div className="text-2xl font-extrabold text-[#005a3c]">{moeda(valor)}</div><div className="mt-1 text-xs">{tipoPessoa==="socio"?"Sócio":"Não sócio"} · {espaco?.nome||"—"}</div></div><button onClick={continuar} className="mt-4 w-full rounded-xl bg-[#005a3c] px-4 py-3 font-extrabold text-white">Continuar</button></aside></section>}
 {!publico&&aba==="reservas"&&<section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold text-[#005a3c]">Reservas cadastradas</h2><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar..." className="rounded-xl border px-3 py-2"/></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#e8f3ee] text-xs font-bold uppercase"><tr><th className="p-3">Data</th><th className="p-3">Espaço</th><th className="p-3">Responsável</th><th className="p-3">Tipo</th><th className="p-3">Valor</th><th className="p-3">Ação</th></tr></thead><tbody>{reservasFiltradas.map(r=><tr key={r.id} className="border-b"><td className="p-3">{dataBR(r.data)}<div className="text-xs text-gray-500">{r.horario}</div></td><td className="p-3">{espacos.find(e=>e.id===r.espacoId)?.nome}</td><td className="p-3 font-bold">{r.nome}</td><td className="p-3">{r.tipoPessoa==="socio"?"Sócio":"Não sócio"}</td><td className="p-3 font-bold text-[#005a3c]">{moeda(r.valor)}</td><td className="p-3">{r.status!=="cancelada"&&<button onClick={()=>cancelar(r.id)} className="rounded-lg bg-red-50 p-2 text-red-600"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</tbody></table></div></section>}
 {!publico&&aba==="admin"&&<section className="space-y-5"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-extrabold text-[#005a3c]">Permissão e valores para não sócios</h2><p className="mt-1 text-sm text-gray-500">Regra: valor de não sócio igual a R$ 0,00 significa bloqueado.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#e8f3ee] text-xs font-bold uppercase"><tr><th className="p-3">Espaço</th><th className="p-3">Sócio</th><th className="p-3">Não sócio</th><th className="p-3">Permissão</th></tr></thead><tbody>{espacos.map(e=><tr key={e.id} className="border-b"><td className="p-3 font-bold">{e.nome}</td><td className="p-3"><input type="number" value={e.precoSocio} onChange={x=>alterarPreco(e.id,"precoSocio",Number(x.target.value))} className="w-28 rounded-lg border px-2 py-2"/></td><td className="p-3"><input type="number" value={e.precoNaoSocio} onChange={x=>alterarPreco(e.id,"precoNaoSocio",Number(x.target.value))} className="w-28 rounded-lg border px-2 py-2"/></td><td className="p-3"><button onClick={()=>alternarNaoSocio(e.id)} disabled={e.precoNaoSocio<=0} className={`rounded-full px-3 py-2 text-xs font-extrabold ${e.precoNaoSocio<=0||!e.permiteNaoSocio?"bg-red-100 text-red-700":"bg-green-100 text-green-700"}`}>{e.precoNaoSocio<=0||!e.permiteNaoSocio?"🔒 Bloqueado":"🟢 Liberado"}</button></td></tr>)}</tbody></table></div></div>
 <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><QrCode className="text-[#005a3c]"/><div><h2 className="text-xl font-extrabold text-[#005a3c]">PIX para reservas</h2><p className="text-sm text-gray-500">A administração cadastra o PIX copia e cola. O sistema gera o QR Code.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs font-bold uppercase text-gray-500">Chave PIX<input value={pixForm.chave_pix} onChange={e=>setPixForm({...pixForm,chave_pix:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-xs font-bold uppercase text-gray-500">Nome do recebedor<input value={pixForm.nome_recebedor} onChange={e=>setPixForm({...pixForm,nome_recebedor:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-xs font-bold uppercase text-gray-500">Cidade<input value={pixForm.cidade} onChange={e=>setPixForm({...pixForm,cidade:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-xs font-bold uppercase text-gray-500 md:col-span-2">PIX copia e cola<input value={pixForm.copia_e_cola} onChange={e=>setPixForm({...pixForm,copia_e_cola:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3" placeholder="Cole aqui o código PIX"/></label></div><button onClick={salvarPix} disabled={salvandoPix} className="mt-4 rounded-xl bg-[#005a3c] px-5 py-3 font-extrabold text-white">{salvandoPix?"Salvando...":"Salvar PIX da administração"}</button></div></section>}
 {etapa==="pagamento"&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-extrabold text-[#005a3c]">{ultimaReserva?"Reserva registrada":"Confirmar reserva"}</h2>{!ultimaReserva&&<div className="mt-4 rounded-xl bg-[#f8faf9] p-4 text-sm space-y-2"><div><b>Responsável:</b> {tipoPessoa==="socio"?socioSelecionado?.nome:nomeNaoSocio}</div><div><b>Espaço:</b> {espaco?.nome}</div><div><b>Data:</b> {dataBR(data)} · {horario}</div><div><b>Total:</b> {moeda(valor)}</div></div>}{!ultimaReserva?<button onClick={confirmar} className="mt-5 w-full rounded-xl bg-[#005a3c] px-4 py-3 font-extrabold text-white">Confirmar reserva</button>:<>{pix?.copia_e_cola?<div className="mt-4 text-center"><div className="inline-block rounded-2xl border p-4"><QRCodeSVG value={pix.copia_e_cola} size={210}/></div><div className="mt-3 font-extrabold">Pague via PIX</div><div className="text-sm text-gray-500">{pix.nome_recebedor}</div><button onClick={copiarPix} className="mt-4 w-full rounded-xl border px-4 py-3 font-bold"><Copy className="mr-2 inline h-4 w-4"/>Copiar PIX copia e cola</button></div>:<div className="mt-4 rounded-xl bg-yellow-50 p-4 text-sm">A administração ainda não cadastrou o PIX para esta reserva.</div>}<button onClick={()=>{setEtapa("selecao");setUltimaReserva(null);setAba(publico?"reservar":"reservas");}} className="mt-3 w-full rounded-xl border px-4 py-3 font-bold">Fechar</button></>}</div></div>}
 </div></main></div>;
}
