"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, ShieldCheck, UserRound, XCircle } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";

type D={socio:{nome:string;matricula:string|number|null;situacao?:string|null;foto_url?:string|null};exame:{label:string;cor:string;validade:string|null};liberado:boolean;acesso?:{entrada_em:string}};
export default function Page(){const[d,setD]=useState<D|null>(null);const[e,setE]=useState("");const[c,setC]=useState(true);
useEffect(()=>{let ok=true;(async()=>{try{const id=new URLSearchParams(location.search).get("id");if(!id)throw new Error("QR Code inválido ou incompleto.");let{data:{session}}=await supabase.auth.getSession();if(!session){session=(await supabase.auth.refreshSession()).data.session}if(!session?.access_token){location.replace(`/login?redirect=${encodeURIComponent(`/acessos/validar?id=${id}`)}`);return}const r=await fetch("/api/acessos/qr",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({id})});const x=await r.json();if(!r.ok)throw new Error(x?.error||"Não foi possível validar a carteirinha.");if(ok)setD(x)}catch(x){if(ok)setE(x instanceof Error?x.message:"Não foi possível validar o QR Code.")}finally{if(ok)setC(false)}})();return()=>{ok=false}},[]);
if(c)return <main className="grid min-h-screen place-items-center bg-[#f8faf9] p-6"><div className="rounded-3xl bg-white p-8 text-center shadow-lg"><Clock3 className="mx-auto h-10 w-10 animate-pulse text-[#005a3c]"/><h1 className="mt-4 text-xl font-black text-[#005a3c]">Validando carteirinha...</h1></div></main>;
if(e)return <main className="grid min-h-screen place-items-center bg-[#f8faf9] p-6"><div className="w-full max-w-md rounded-3xl bg-white p-8 text-center shadow-lg"><XCircle className="mx-auto h-14 w-14 text-red-500"/><h1 className="mt-4 text-2xl font-black text-red-700">Não foi possível validar</h1><p className="mt-2 text-gray-600">{e}</p><p className="mt-5 text-xs text-gray-400">O funcionário deve estar logado no sistema para validar o QR Code.</p></div></main>;
if(!d)return null;const ex=d.exame.cor==="verde"?"bg-green-50 text-green-700 border-green-200":d.exame.cor==="amarelo"?"bg-yellow-50 text-yellow-800 border-yellow-200":d.exame.cor==="vermelho"?"bg-red-50 text-red-700 border-red-200":"bg-gray-50 text-gray-600 border-gray-200";
return <main className="min-h-screen bg-[#f8faf9] p-4 sm:p-8"><div className="mx-auto max-w-md space-y-4"><div className="rounded-3xl bg-[#005a3c] p-6 text-white shadow-xl"><div className="flex items-center gap-3"><ShieldCheck className="h-8 w-8"/><div><div className="text-xs font-bold uppercase tracking-widest text-white/70">Portaria · Sociedade Guarani</div><h1 className="text-2xl font-black">Validação de acesso</h1></div></div></div><section className={`rounded-3xl border p-6 shadow-lg ${d.liberado?"border-green-200 bg-green-50":"border-red-200 bg-red-50"}`}>{d.liberado?<CheckCircle2 className="h-14 w-14 text-green-600"/>:<XCircle className="h-14 w-14 text-red-600"/>}<h2 className={`mt-3 text-3xl font-black ${d.liberado?"text-green-700":"text-red-700"}`}>{d.liberado?"ENTRADA LIBERADA":"ACESSO BLOQUEADO"}</h2><div className="mt-5 flex items-center gap-4 rounded-2xl bg-white/80 p-4">{d.socio.foto_url?<img src={d.socio.foto_url} alt="Foto do associado" className="h-20 w-20 rounded-2xl object-cover"/>:<div className="grid h-20 w-20 place-items-center rounded-2xl bg-gray-100"><UserRound className="h-9 w-9 text-gray-400"/></div>}<div><div className="text-xl font-black text-[#17382c]">{d.socio.nome}</div><div className="text-sm text-gray-600">Matrícula: <b>{d.socio.matricula||"—"}</b></div><div className="text-sm text-gray-600">Situação: <b>{d.socio.situacao||"Não informada"}</b></div></div></div><div className={`mt-4 rounded-2xl border p-4 ${ex}`}><div className="font-black">Exame médico: {d.exame.label}</div><div className="mt-1 text-sm">Validade: {d.exame.validade?new Date(`${d.exame.validade}T12:00:00`).toLocaleDateString("pt-BR"):"Não informada"}</div></div><div className="mt-4 text-xs text-gray-500">Entrada registrada automaticamente em {d.acesso?.entrada_em?new Date(d.acesso.entrada_em).toLocaleString("pt-BR"):"agora"}.</div></section></div></main>}
