import {NextResponse} from "next/server";
import {getServiceClient,exigirAdministrador} from "@/lib/guaraniAuth";
export const dynamic="force-dynamic";
function comp(a:number,m:number){return `${a}-${String(m).padStart(2,"0")}-01`}
function venc(a:number,m:number,d:number){const last=new Date(a,m,0).getDate();return `${a}-${String(m).padStart(2,"0")}-${String(Math.min(Math.max(d||10,1),last)).padStart(2,"0")}`}
async function auth(r:Request){const x=await exigirAdministrador(r);if("error"in x)return{response:NextResponse.json({error:x.error},{status:x.status})};return{db:getServiceClient()}}
export async function GET(r:Request){const x=await auth(r);if("response"in x)return x.response;try{const u=new URL(r.url),a=+(u.searchParams.get("ano")||new Date().getFullYear()),m=+(u.searchParams.get("mes")||new Date().getMonth()+1),c=comp(a,m);const [{data:ms,error:me},{data:cs,error:ce}]=await Promise.all([x.db.from("mensalidades").select("id,socio_id,competencia,valor,data_vencimento,situacao,data_pagamento,tipo_pagamento,observacoes,motivo").eq("competencia",c).order("data_vencimento"),x.db.from("configuracoes_mensalidades").select("*").eq("ativo",true).order("vigencia_inicio",{ascending:false})]);if(me)throw me;if(ce)throw ce;const ids=(ms||[]).map(z=>z.socio_id);const{data:ss,error:se}=ids.length?await x.db.from("socios").select("id,nome,matricula,tipo_socio,responsavel_id").in("id",ids):{data:[],error:null}as any;if(se)throw se;const map=new Map((ss||[]).map((s:any)=>[String(s.id),s]));return NextResponse.json({mensalidades:(ms||[]).map((z:any)=>({...z,socio:map.get(String(z.socio_id))||null})),configuracoes:cs||[]})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Erro ao carregar mensalidades."},{status:500})}}
export async function POST(r:Request){const x=await auth(r);if("response"in x)return x.response;try{const b=await r.json(),a=String(b.acao||"");if(a==="config_criar"){const{data,error}=await x.db.from("configuracoes_mensalidades").insert({tipo_socio:String(b.tipo_socio||"").trim(),nome:String(b.nome||"").trim(),valor:+b.valor||0,vigencia_inicio:String(b.vigencia_inicio||"").slice(0,10),ativo:true}).select().single();if(error)throw error;return NextResponse.json({config:data,message:"Tipo de mensalidade adicionado."})}if(a==="config_editar"){const id=String(b.id||"");if(!id)return NextResponse.json({error:"Configuração não informada."},{status:400});const{error}=await x.db.from("configuracoes_mensalidades").update({tipo_socio:String(b.tipo_socio||"").trim(),nome:String(b.nome||"").trim(),valor:+b.valor||0,vigencia_inicio:String(b.vigencia_inicio||"").slice(0,10),updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;return NextResponse.json({message:"Configuração atualizada."})}if(a==="gerar"){const ano=+b.ano,mes=+b.mes,c=comp(ano,mes);const{data:cs,error:ce}=await x.db.from("configuracoes_mensalidades").select("*").eq("ativo",true).lte("vigencia_inicio",c).order("vigencia_inicio",{ascending:false});if(ce)throw ce;const mapa=new Map<string,any>();for(const z of cs||[])if(!mapa.has(z.tipo_socio))mapa.set(z.tipo_socio,z);const{data:ss,error:se}=await x.db.from("socios").select("id,tipo_socio,possui_mensalidade,valor_mensalidade,dia_vencimento,tipo_pagamento,situacao").eq("possui_mensalidade",true).neq("situacao","inativo");if(se)throw se;const{data:ex,error:ee}=await x.db.from("mensalidades").select("socio_id").eq("competencia",c);if(ee)throw ee;const set=new Set((ex||[]).map((z:any)=>String(z.socio_id)));const novos=(ss||[]).filter((s:any)=>String(s.tipo_socio)!=="remido"&&!set.has(String(s.id))).map((s:any)=>{const cfg=mapa.get(s.tipo_socio);const valor=cfg?+cfg.valor:+s.valor_mensalidade||0;return{socio_id:s.id,competencia:c,valor,data_vencimento:venc(ano,mes,+s.dia_vencimento||10),situacao:valor===0?"isento":"em_aberto",tipo_pagamento:s.tipo_pagamento||null,observacoes:null,motivo:null}});if(novos.length){const{error}=await x.db.from("mensalidades").insert(novos);if(error)throw error}return NextResponse.json({gerados:novos.length,message:`${novos.length} mensalidade(s) gerada(s).`})}if(a==="baixar"){const ids=(b.ids||[]).map(String);if(!ids.length)return NextResponse.json({error:"Selecione mensalidades."},{status:400});const d=String(b.data_pagamento||new Date().toISOString().slice(0,10));const{error}=await x.db.from("mensalidades").update({situacao:"pago",data_pagamento:d}).in("id",ids);if(error)throw error;return NextResponse.json({message:`${ids.length} mensalidade(s) baixada(s).`})}return NextResponse.json({error:"Ação inválida."},{status:400})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Erro ao processar mensalidades."},{status:500})}}

